services:
    mongo:
        image: mongo:latest
        container_name: innogram_mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    redis:
        image: redis:latest
        container_name: innogram_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    postgres:
        image: postgres:latest
        container_name: innogram_postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
    mongo_data:
        driver: local
    redis_data:
        driver: local
    postgres_data:
        driver: local
